### ISSUE TITLE
Icons disappearing on hover

### ISSUE THREAD

**Issue by delixyr** [TheZoker/ComBoot-3.1#27]
All the icons and elements are dissapearing me on hover

screencast : https://www.dropbox.com/s/m2cxjo69yo1djtm/2015-08-05_16-18-15.mp4?dl=0

**Comment by TheZoker** [comment]
WTF :O

I've never seen a issue like that... 
Can you please provide me the page url?

**Comment by delixyr** [comment]
The website is in localhost. Actually I am trying to embed phpbb within joomla site using p8pbb bridge.
And the joomla template is bootstrap 2 based. So it must be a BS conflict?

**Comment by TheZoker** [comment]
Never tried that, but there is nothing what would lead the buttons to disappear...
May you switch to a joomla template that support bs3 just for test purpose?

**Comment by TheZoker** [comment]
Im closing this issue for now, because its not related to the theme it selfe.
You can provide me a link (if you upload your project) and I will have a look.
