### ISSUE TITLE
Attachment list

### ISSUE THREAD

**Issue by SirSheep** [TheZoker/ComBoot-3.1#28]
I may have found a bug with attachment uploads. On the post editor page, the first time you load a file, no list of attachments comes up. Clicking the preview button brings it up. After that, it updates the list normally when files are added or deleted.

**Comment by TheZoker** [comment]
Can you attach a screenshot of that behavior?

**Comment by SirSheep** [comment]
Sure thing! The screenshots are below.

The first image is right after uploading a file. The second image is after "Preview" is clicked. The third image is after a new image is added (no other buttons were clicked). The file list does get updated on Prosilver, so it's probably just a missing line of code in attachment.html or posting_attach_body.html.

![capture](https://cloud.githubusercontent.com/assets/4268923/9156986/2e437e9e-3eba-11e5-951c-35bc8bd7f190.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4268923/9156987/304ec2c0-3eba-11e5-8ce7-c90242567695.PNG)
![capture3](https://cloud.githubusercontent.com/assets/4268923/9156989/31a999ec-3eba-11e5-855f-671ef449272b.PNG)

**Comment by TheZoker** [comment]
I will have a look at it.

**Comment by TheZoker** [comment]
Please test it and tell me if it works.
